### ISSUE TITLE
Inference not working properly

### ISSUE THREAD

**Issue by nicolemcnally** [hkproj/pytorch-paligemma#6]
When i run inference, the same token is generated for every step and so the output is just spaces (108 token).

**Comment by nicolemcnally** [comment]
issue was because i was using the paligemma2 model.

**Comment by xiaonengmiao** [comment]
> issue was because i was using the paligemma2 model.

After switch to paligemma1 model, did u get the same result: "this building is the oldest clock tower in the world"

My result is "this building is the oldest" then eos token is generated
